config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    # resources :comments, only: [:new, :create, :edit]
    resources :comments
  end

  root to: 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  has_rich_text :body

  broadcasts_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_rich_text :body
  has_many :comments, dependent: :destroy

  broadcasts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_tweet
  before_action :set_tweet_and_comment, only: [:show, :edit, :update, :destroy]

  def new
    @comment = @tweet.comments.new
  end

  def show
  end

  def create
    @comment = @tweet.comments.create!(comment_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @tweet}
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @tweet, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

  def set_tweet_and_comment
    # @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <%= content_tag :div do %>
    <em>Someone said <%= time_ago_in_words(comment.created_at) %> ago</em>
    <%= comment.body %>
    <%#= link_to 'ssshow', tweet_comment_path(@tweet, comment) unless @comment%>
    <%= link_to 'edit', edit_tweet_comment_path(@tweet, comment) %>
    <hr>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@tweet, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= button_to 'cancel', tweet_path(@tweet), 'data-turbo-frame': :_top %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Post</h1>

<%= turbo_frame_tag dom_id(@comment) do %>
  <%= render 'form', comment: @comment %>
<% end %>

<%#= link_to 'Show', @tweet %>
<%= link_to 'Back', tweet_path(@tweet) %>

app/views/comments/new.html.erb
<%= turbo_frame_tag 'new_comment' do %>
  <h2>New Comment</h2>
  <%= form_with model: [@tweet, @comment],
    data: { controller: 'reset_form', action: 'turbo:submit-end->reset_form#reset' } do |form| %>
    <div class='field'>
      <%= form.rich_text_area :body %>
      <%= form.submit 'Post', 'data-reset_form-target': 'button' %>
    </div>
  <% end %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_stream_from @comment %>

<%= render @comment %>

<%= link_to 'Edit', edit_tweet_comment_path(@tweet, @comment) %> |
<%= link_to 'Back', tweet_path(@tweet), 'data-turbo-frame': :_top %>

<%#= link_to 'New Comment', new_tweet_comment_path(@comment) %> | 
<%#= link_to 'Edit', edit_tweet_comment_path(@comment) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= content_tag :div, id: dom_id(tweet) do %>
  <h1><%= tweet.title %></h1>
  <p><%= tweet.body %></p>
<% end %>

app/views/tweets/edit.html.erb
<%= turbo_frame_tag 'tweet' do %>
  <h1>Editing Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>
<% end %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.title %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<%= turbo_stream_from @tweet %>

<%= turbo_frame_tag 'tweet' do %>
  <%= render @tweet %>

  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <%= link_to 'Back', tweets_path, 'data-turbo-frame': :_top %>
<% end %>

<div id='comments'>
  <h2>Comments</h2>
  <%= render @tweet.comments %>
</div>

<%= link_to 'New Comment', new_tweet_comment_path(@tweet) %> 
<%#= link_to 'Edit', edit_tweet_comment_path(@tweet) %>